name : New workflow
run-name: New workflow

on: [push]

jobs: 
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Run one-line script
              run: echo "Hello, world"
            - name: Print secret
              run: echo ${{ secrets.TEST }}
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Run some tests
              run: echo "Run some tests"
              