name : CI

on: [push]

jobs: 
    build:
        runs-only: ubuntu-latest
        steps:
            - uses: action/checkout@v4
            - name: Run one-line script
              run: echo "Hello, world"
